[build-system]
requires = ["setuptools >= 38.6.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pylint.master]
jobs = 0
load-plugins = [
    "pylint_django",
]

[tool.pylint.format]
max-line-length = 119

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",

    "bad-continuation",
    "bad-whitespace",
]

[tool.pylint.variables]
ignored-argument-names = "kwargs|args"


[tool.isort]
combine_as_imports = true
include_trailing_comma = true
known_first_party = "thepoint"
line_length = 119
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true


[tool.black]
line-length = 119
include = '\.pyi?$'
