[project]
name = "thepoint"
version = "2025.6.14"
description = "A Django project for The Point Church's website."
license = "GPL-2.0-only"
readme = "README.md"
requires-python = ">=3.13,<3.15"
authors = [
    {name = "Craig Holyoak", email = "craig@helmsdeep.org"},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dependencies = [
    "django (>=6.1,<6.2.0)",
]

[project.urls]
homepage = "https://github.com/thepointchurch/thepoint"
repository = "https://github.com/thepointchurch/thepoint"

[dependency-groups]
dev = [
    "coverage>=7,<8",
    "gitpython>=3,<4",
    "pre-commit>=4,<5",
    "pylint>=3,<4",
    "semantic_version>=2,<3",
    "tomlkit>=0,<1",
]

[tool.uv]

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"


[tool.pylint.master]
jobs = 0

[tool.pylint.format]
max-line-length = 119

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "duplicate-code",
]

[tool.pylint.variables]
ignored-argument-names = "kwargs|args"


[tool.isort]
combine_as_imports = true
include_trailing_comma = true
known_first_party = "upperroom"
line_length = 119
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true


[tool.black]
line-length = 119
include = '\.pyi?$'
