name: Docker Image

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - testing
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'docker-compose.yml'
  schedule:
    - cron: '30 18 * * 5'
  workflow_dispatch:

env:
  IMAGE_NAME: thepoint

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install tomlkit gitpython semantic_version

      - name: Set version
        id: version
        env:
          PYTHONPATH: .
        run: |
          import os
          import pathlib
          from version import update_version
          pathlib.Path(os.environ["GITHUB_OUTPUT"]).write_text(f"version={update_version()}")
        shell: python

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # yamllint disable rule:line-length
      - name: Set up Docker image tags
        id: set_tags
        run: |
          IMAGE_ID=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')
          BRANCH="$(git branch --show-current)"
          if [ "$BRANCH" = "master" ]; then
          echo "tags=ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest,ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ steps.version.outputs.version }},${{ github.repository }}:latest,${{ github.repository }}:${{ steps.version.outputs.version }}" >>$GITHUB_OUTPUT
          elif [ -z "$BRANCH" ]; then
              TAG="$(git describe --tags)"
              echo "tags=ghcr.io/${{ github.repository }}/$IMAGE_NAME:$TAG,${{ github.repository }}:$TAG" >>$GITHUB_OUTPUT
          else
              echo "tags=ghcr.io/${{ github.repository }}/$IMAGE_NAME:$BRANCH,${{ github.repository }}:$BRANCH" >>$GITHUB_OUTPUT
          fi
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>$GITHUB_OUTPUT
          if [ "$BRANCH" = "master" -o -z "$BRANCH" ]; then
              echo "upperroom_version=latest" >>$GITHUB_OUTPUT
          else
              echo "upperroom_version=$BRANCH" >>$GITHUB_OUTPUT
          fi
      # yamllint enable rule:line-length

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            "version=${{ steps.version.outputs.version }}"
            "build_date=${{ steps.set_tags.outputs.build_date }}"
            "upperroom_version=${{ steps.set_tags.outputs.upperroom_version }}"
          push: true
          tags: ${{ steps.set_tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
